CREATE OR REPLACE SHARE SHARE_OUTPUT;

GRANT USAGE ON DATABASE DEVELOPMENT TO SHARE SHARE_OUTPUT;
GRANT USAGE ON SCHEMA FINAL_SCHEMA TO SHARE SHARE_OUTPUT;
GRANT SELECT ON TABLE DEVELOPMENT.FINAL_SCHEMA.LOAN TO SHARE SHARE_OUTPUT;
GRANT SELECT ON TABLE DEVELOPMENT.FINAL_SCHEMA.ORDERS TO SHARE SHARE_OUTPUT;

SHOW TABLES;

SHOW GRANTS TO SHARE SHARE_OUTPUT;

CREATE MANAGED ACCOUNT READER_ACCOUNT_NAME
ADMIN_NAME = READER-ACCOUNT-USER_NAME,
ADMIN_PASSWORD = 'READER-ACCOUNT-PASSWORD'
TYPE = READER;

SHOW MANAGED ACCOUNTS;

ALTER SHARE SHARE_OUTPUT ADD ACCOUNT = ACCOUNT-LOCATOR;

-- ONCE THE READER ACCOUNT IS CREATED NEED TO LOGIN WITH THE CREDENTIALS AND FOLLOW BELOW QUERIE.

CREATE DATABASE OUTPUT_SHARE FROM SHARE FULLNAME.SHARE_OUTPUT; -- DATABASE WILL CREATE FOR READ, CAN'T PERFORM ANY DIRECT DML OPERATIONS
